version: '3'
services:
  columnservice:
    image: "coffeateam/coffea-columnservice:dev"
    command: uvicorn --host 0.0.0.0 columnservice.server:app
    ports:
      - "8000:8000"
    volumes:
      - .:/src/columnservice
      - ${X509_USER_PROXY}:/tmp/proxy
    environment:
      MONGODB_USERNAME: "coffea"
      MONGODB_PASSWORD: "coffea"
      MONGODB_DATABASE: "coffeadb"
      MONGODB_HOSTNAME: "mongodb"
      DASK_SCHEDULER: "tls://dask-scheduler:8786"
      X509_USER_PROXY: "/tmp/proxy"
      MINIO_HOSTNAME: "minio:9000"
      MINIO_ACCESS_KEY: "miniocoffeakey"
      MINIO_SECRET_KEY: "miniocoffeakey"
      COLUMNSERVICE_BUCKET: "columnservice"
      USER_ALLOWLIST: "ncsmith"
      TLS_PATH: "/src/columnservice"
  mongodb:
    image: "bitnami/mongodb:latest"
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_PASSWORD: "password123"
      MONGODB_USERNAME: "coffea"
      MONGODB_PASSWORD: "coffea"
      MONGODB_DATABASE: "coffeadb"
  minio:
    image: "bitnami/minio:latest"
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "miniocoffeakey"
      MINIO_SECRET_KEY: "miniocoffeakey"
      MINIO_SKIP_CLIENT: "yes"
  dask-scheduler:
    image: "coffeateam/coffea-columnservice:dev"
    command: dask-scheduler --tls-ca-file /src/columnservice/ca.crt --tls-cert /src/columnservice/hostcert.pem
    volumes:
      - .:/src/columnservice
    ports:
      - "8786:8786"
      - "8787:8787"
  dask-worker:
    image: "coffeateam/coffea-columnservice:dev"
    command: dask-worker --tls-ca-file /src/columnservice/ca.crt --tls-cert /src/columnservice/hostcert.pem tls://dask-scheduler:8786
    volumes:
      - ${X509_USER_PROXY}:/tmp/proxy
      - .:/src/columnservice
    environment:
      X509_USER_PROXY: "/tmp/proxy"
      COLUMNSERVICE_URL: "http://columnservice:8000"
  jupyter:
    image: "coffeateam/coffea-columnservice:dev"
    command: jupyter notebook --no-browser --ip 0.0.0.0 --port 8880
    user: "1000:1000"
    ports:
      - "8880:8880"
    volumes:
      - ${X509_USER_PROXY}:/tmp/proxy
      - .:/src/columnservice
      - ./jupyter:/opt/app
    environment:
      HOME: "/opt/app"
      X509_USER_PROXY: "/tmp/proxy"
      COLUMNSERVICE_URL: "http://columnservice:8000"
